# Generated by Django 6.1.1 on 2026-10-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bhk', models.PositiveSmallIntegerField(default=2)),
                ('property_type', models.CharField(default='Apartment', max_length=100)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furnishing', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], default='Unfurnished', max_length=30)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Needs Repair', 'Needs Repair')], default='Good', max_length=30)),
                ('area_sqft', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveSmallIntegerField(default=2)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(default='Ahmedabad', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('parking', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
