# Generated by Django 6.1.1 on 2026-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='json_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(default='Unfurnished', max_length=50),
        ),
    ]
